### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mamootrahal** [MartinSGill/SubnauticaWatcher#22] opened 2018-02-22 09:30 UTC
Endless loading.
![3](https://user-images.githubusercontent.com/36728380/36530473-30a066a0-17cc-11e8-82dd-c7ec30242c7e.jpg)

**Comment by MartinSGill** [comment] 2018-02-22 11:56
I've had this reported a couple of times now.  But I've not been able to reproduce it.

See #16  for some tips that others have found.

**Comment by MartinSGill** [comment] 2018-02-22 11:56
duplicate of #16.

**Closed as completed by MartinSGill** 2018-02-22 11:56 UTC
Labels: duplicate
