### ISSUE TITLE
Add biom legend.

### ISSUE THREAD

**Issue by Vlad-00003** [MartinSGill/SubnauticaWatcher#24] opened 2018-02-26 17:10 UTC
Hi! First of all - cool mod! It helps me a lot, and even more that a lot...
But - at the beginning I didn't know wich color represents each biom.
Right now I've found the info on wiki, but... It's a gif. And I have to wait for the desired biom to be shown.
In my opinion - it would be better if the map would have the legend, so the players can easily see where they need to go =)
Thanks again for the mod, really love it! <3

**Comment by MartinSGill** [comment] 2018-02-26 17:13
duplicate of #11

**Closed as completed by MartinSGill** 2018-02-26 17:13 UTC
Labels: duplicate

**Comment by Vlad-00003** [comment] 2018-02-26 17:22
@MartinSGill, I don't get it. Why can't you just add a menu on the right bar that would show what color mean what? O_o

**Comment by MartinSGill** [comment] 2018-02-27 15:09
It's already been done. I just haven't published an update yet.

**Comment by Vlad-00003** [comment] 2018-02-27 15:20
Oh.... I see. Then sorry to bother you =3
Waiting for the update now, thanks (^^)/
